# ローカル開発用
version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app
    # コンテナ立ち上げ時に実行されるコマンド
    # pipenvによるパッケージインストール（コンテナ内では仮想環境化せず、グローバルインストールさせる）
    command: >
      bash -c "pipenv install --dev --system && sleep infinity"
    # コンテナ内のカレントディレクトリ指定
    working_dir: /app
    tty: true
    stdin_open: true
    env_file:
      - .env
      - .env.common
